/*
 * This file is generated by jOOQ.
*/
package com.farwolf.updater.auto;


import com.farwolf.updater.auto.tables.Hotupadte;
import com.farwolf.updater.auto.tables.Version;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends SchemaImpl {

    private static final long serialVersionUID = -1059201653;

    /**
     * The reference instance of <code>app</code>
     */
    public static final App APP = new App();

    /**
     * The table <code>app.app</code>.
     */
    public final com.farwolf.updater.auto.tables.App APP_ = com.farwolf.updater.auto.tables.App.APP_;

    /**
     * The table <code>app.hotupadte</code>.
     */
    public final Hotupadte HOTUPADTE = com.farwolf.updater.auto.tables.Hotupadte.HOTUPADTE;

    /**
     * The table <code>app.version</code>.
     */
    public final Version VERSION = com.farwolf.updater.auto.tables.Version.VERSION;

    /**
     * No further instances allowed
     */
    private App() {
        super("app", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            com.farwolf.updater.auto.tables.App.APP_,
            Hotupadte.HOTUPADTE,
            Version.VERSION);
    }
}
