/*
 * This file is generated by jOOQ.
*/
package com.farwolf.updater.auto;


import com.farwolf.updater.auto.tables.App;
import com.farwolf.updater.auto.tables.Hotupadte;
import com.farwolf.updater.auto.tables.Version;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in app
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>app.app</code>.
     */
    public static final App APP_ = com.farwolf.updater.auto.tables.App.APP_;

    /**
     * The table <code>app.hotupadte</code>.
     */
    public static final Hotupadte HOTUPADTE = com.farwolf.updater.auto.tables.Hotupadte.HOTUPADTE;

    /**
     * The table <code>app.version</code>.
     */
    public static final Version VERSION = com.farwolf.updater.auto.tables.Version.VERSION;
}
