/*
 * This file is generated by jOOQ.
*/
package com.farwolf.updater.auto.tables;


import com.farwolf.updater.auto.App;
import com.farwolf.updater.auto.Keys;
import com.farwolf.updater.auto.tables.records.HotupadteRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hotupadte extends TableImpl<HotupadteRecord> {

    private static final long serialVersionUID = 1518404463;

    /**
     * The reference instance of <code>app.hotupadte</code>
     */
    public static final Hotupadte HOTUPADTE = new Hotupadte();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HotupadteRecord> getRecordType() {
        return HotupadteRecord.class;
    }

    /**
     * The column <code>app.hotupadte.id</code>.
     */
    public final TableField<HotupadteRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>app.hotupadte.url</code>.
     */
    public final TableField<HotupadteRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

    /**
     * The column <code>app.hotupadte.js_version</code>.
     */
    public final TableField<HotupadteRecord, Integer> JS_VERSION = createField("js_version", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>app.hotupadte.native_version</code>.
     */
    public final TableField<HotupadteRecord, Integer> NATIVE_VERSION = createField("native_version", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>app.hotupadte.mode</code>. 0:静默更新；1.提示更新；2.强制更新
     */
    public final TableField<HotupadteRecord, Integer> MODE = createField("mode", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "0:静默更新；1.提示更新；2.强制更新");

    /**
     * The column <code>app.hotupadte.size</code>.
     */
    public final TableField<HotupadteRecord, String> SIZE = createField("size", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>app.hotupadte.systemtype</code>.
     */
    public final TableField<HotupadteRecord, Integer> SYSTEMTYPE = createField("systemtype", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>app.hotupadte.app_id</code>.
     */
    public final TableField<HotupadteRecord, Integer> APP_ID = createField("app_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>app.hotupadte</code> table reference
     */
    public Hotupadte() {
        this("hotupadte", null);
    }

    /**
     * Create an aliased <code>app.hotupadte</code> table reference
     */
    public Hotupadte(String alias) {
        this(alias, HOTUPADTE);
    }

    private Hotupadte(String alias, Table<HotupadteRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hotupadte(String alias, Table<HotupadteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return App.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<HotupadteRecord, Long> getIdentity() {
        return Keys.IDENTITY_HOTUPADTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HotupadteRecord> getPrimaryKey() {
        return Keys.KEY_HOTUPADTE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HotupadteRecord>> getKeys() {
        return Arrays.<UniqueKey<HotupadteRecord>>asList(Keys.KEY_HOTUPADTE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Hotupadte as(String alias) {
        return new Hotupadte(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hotupadte rename(String name) {
        return new Hotupadte(name, null);
    }
}
