/*
 * This file is generated by jOOQ.
*/
package com.farwolf.updater.auto.tables.records;


import com.farwolf.updater.auto.tables.Hotupadte;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HotupadteRecord extends UpdatableRecordImpl<HotupadteRecord> implements Record8<Long, String, Integer, Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -1711819977;

    /**
     * Setter for <code>app.hotupadte.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.hotupadte.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>app.hotupadte.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.hotupadte.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>app.hotupadte.js_version</code>.
     */
    public void setJsVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.hotupadte.js_version</code>.
     */
    public Integer getJsVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>app.hotupadte.native_version</code>.
     */
    public void setNativeVersion(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>app.hotupadte.native_version</code>.
     */
    public Integer getNativeVersion() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>app.hotupadte.mode</code>. 0:静默更新；1.提示更新；2.强制更新
     */
    public void setMode(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>app.hotupadte.mode</code>. 0:静默更新；1.提示更新；2.强制更新
     */
    public Integer getMode() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>app.hotupadte.size</code>.
     */
    public void setSize(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>app.hotupadte.size</code>.
     */
    public String getSize() {
        return (String) get(5);
    }

    /**
     * Setter for <code>app.hotupadte.systemtype</code>.
     */
    public void setSystemtype(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>app.hotupadte.systemtype</code>.
     */
    public Integer getSystemtype() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>app.hotupadte.app_id</code>.
     */
    public void setAppId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>app.hotupadte.app_id</code>.
     */
    public Integer getAppId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Integer, Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Integer, Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Hotupadte.HOTUPADTE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Hotupadte.HOTUPADTE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Hotupadte.HOTUPADTE.JS_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Hotupadte.HOTUPADTE.NATIVE_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Hotupadte.HOTUPADTE.MODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Hotupadte.HOTUPADTE.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Hotupadte.HOTUPADTE.SYSTEMTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Hotupadte.HOTUPADTE.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getJsVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getNativeVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSystemtype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord value2(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord value3(Integer value) {
        setJsVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord value4(Integer value) {
        setNativeVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord value5(Integer value) {
        setMode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord value6(String value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord value7(Integer value) {
        setSystemtype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord value8(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HotupadteRecord values(Long value1, String value2, Integer value3, Integer value4, Integer value5, String value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HotupadteRecord
     */
    public HotupadteRecord() {
        super(Hotupadte.HOTUPADTE);
    }

    /**
     * Create a detached, initialised HotupadteRecord
     */
    public HotupadteRecord(Long id, String url, Integer jsVersion, Integer nativeVersion, Integer mode, String size, Integer systemtype, Integer appId) {
        super(Hotupadte.HOTUPADTE);

        set(0, id);
        set(1, url);
        set(2, jsVersion);
        set(3, nativeVersion);
        set(4, mode);
        set(5, size);
        set(6, systemtype);
        set(7, appId);
    }
}
