/*
 * This file is generated by jOOQ.
*/
package com.farwolf.updater.auto.tables.records;


import com.farwolf.updater.auto.tables.Version;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VersionRecord extends UpdatableRecordImpl<VersionRecord> implements Record10<Long, String, String, Integer, Integer, Integer, String, String, String, String> {

    private static final long serialVersionUID = 113635330;

    /**
     * Setter for <code>app.version.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.version.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>app.version.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.version.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>app.version.version_name</code>.
     */
    public void setVersionName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.version.version_name</code>.
     */
    public String getVersionName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app.version.version_code</code>.
     */
    public void setVersionCode(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>app.version.version_code</code>.
     */
    public Integer getVersionCode() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>app.version.system_type</code>.
     */
    public void setSystemType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>app.version.system_type</code>.
     */
    public Integer getSystemType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>app.version.app_id</code>.
     */
    public void setAppId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>app.version.app_id</code>.
     */
    public Integer getAppId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>app.version.desc</code>.
     */
    public void setDesc(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>app.version.desc</code>.
     */
    public String getDesc() {
        return (String) get(6);
    }

    /**
     * Setter for <code>app.version.download_url</code>.
     */
    public void setDownloadUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>app.version.download_url</code>.
     */
    public String getDownloadUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>app.version.source</code>.
     */
    public void setSource(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>app.version.source</code>.
     */
    public String getSource() {
        return (String) get(8);
    }

    /**
     * Setter for <code>app.version.size</code>.
     */
    public void setSize(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>app.version.size</code>.
     */
    public String getSize() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Integer, Integer, Integer, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, Integer, Integer, Integer, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Version.VERSION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Version.VERSION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Version.VERSION.VERSION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Version.VERSION.VERSION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Version.VERSION.SYSTEM_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Version.VERSION.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Version.VERSION.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Version.VERSION.DOWNLOAD_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Version.VERSION.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Version.VERSION.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getVersionName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getVersionCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getSystemType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDownloadUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value3(String value) {
        setVersionName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value4(Integer value) {
        setVersionCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value5(Integer value) {
        setSystemType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value6(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value7(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value8(String value) {
        setDownloadUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value9(String value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord value10(String value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionRecord values(Long value1, String value2, String value3, Integer value4, Integer value5, Integer value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VersionRecord
     */
    public VersionRecord() {
        super(Version.VERSION);
    }

    /**
     * Create a detached, initialised VersionRecord
     */
    public VersionRecord(Long id, String name, String versionName, Integer versionCode, Integer systemType, Integer appId, String desc, String downloadUrl, String source, String size) {
        super(Version.VERSION);

        set(0, id);
        set(1, name);
        set(2, versionName);
        set(3, versionCode);
        set(4, systemType);
        set(5, appId);
        set(6, desc);
        set(7, downloadUrl);
        set(8, source);
        set(9, size);
    }
}
